### ISSUE TITLE
ref as callback / afterRender on any element?

### ISSUE THREAD

**Issue by bluenote10** [ryansolid/babel-plugin-jsx-dom-expressions#14]
I'm wondering if it would make sense to support `afterRender` on any element, not just within `<$>` (maybe that's about to change with the refactoring anyway?).

Example use case: Implementing a `RenderMarkdown` component. This would typically involve something like `el.innerHTML = convertMarkdownStringToHTML(markdown)`. Currently `afterRender` is only support by `<$>` control flow, which makes it a bit awkward to use in unconditional situations:

```js
<$ when={true}
  afterRender={(firstEl, nextSibling) => {
    firstEl.innerHTML = convertMarkdown(props.note.markdown)
  }}
>
  <div class="markdown-wrapper"></div>
</$>
```

Is it possible to simplify this to something like:

```js
<div class="markdown-wrapper" afterRender={ el => {
  el.innerHTML = convertMarkdown(props.note.markdown) 
}}></div>
```

Alternatively, `ref` could take a callback like in React?

Speaking of the `afterRender` API: I'm wondering why `afterRender` takes both `firstEl` and `nextSibling` as argument. Isn't `nextSibling` redundant, because it is possible to call `nextSibling` on the given element?

**Comment by ryansolid** [comment]
Hmmm.. `ref` as a function might be a better design. I copied Surplus' convention since it is so simple, but the timing of resolution seems to cause endless confusion. Right now custom directives and `forwardRef` both work with functions. I didn't intend `forwardRef` for this purpose but it works. If I change refs to all be functions I can actually remove `forwardRef` altogether since you can just pass the function all the way through. This worth putting out there. I can't support both forms since the current ref mechanism is a compilation trick, and can't be checked at runtime. It's one way or the other.

But what you are looking for really seems like a custom directive. You can have the runtime run an arbitrary method of your choosing. It provides a mechanism to encapsulate DOM manipulation out of the view. This provides a sort of escape hatch for binding mechanism the core library doesn't provide.

It works like this:

```jsx
const markdown = (el, accessor) => el.innerHTML = convertMarkdown(accessor());

<div class="markdown-wrapper" $markdown={props.note.markdown} />
```

`afterRender` works a bit different in that it calls after each update. It is a mechanism to handle the dynamic nature of the control flow whereas the children might be different elements. `afterRender` returns a range of elements since with the insertion of fragments (which lose their children on insertion) it may not be a single node, especially with the `each` control flow.

That being said I haven't figured out how to handle afterRender with the new refactor work, or what mechanism makes sense. When I had control flow I had access to the DOM in the update cycle. Now I only have access to the intermediate data (which may be DOM nodes) but are not guaranteed to be the final state.

**Comment by bluenote10** [comment]
Regarding directives: It wasn't clear to me that the update semantics are the same as `afterRender` and initially I couldn't get them to work in TypeScript. Out of the box they don't compile, because a custom `$___` attribute is not allowed as per the interface definition. To make it work it's necessary to extend the `HTMLAttributes` interface e.g.:

```ts
declare global {
  namespace JSX {
    interface HTMLAttributes<T> {
      $markdown?: string
    }
  }
}
```
There will also be a compiler warning (`const markdown` is unused), because the compiler isn't aware of the hidden usage.

In my opinion, a callback solution would be more readable (less magic / special knowledge required) and more TypeScript friendly.

**Comment by ryansolid** [comment]
They aren't exactly the same as `afterRender`. With the refactor I'm doing `afterRender` goes away though and basically these ref like things will be all that remain. I'm going to introduce something to accomplish similar things but it won't be the same. Separating the reactivity from the DOM updates means we will have to rely on afterEffects or similar scheduling to handle after DOM updates. The new approach will be more consistent but more abstracted from rendering cycle.

Hmm.. I guess that is why Surplus uses `fn` over and over. The thing is you want to be able to support more than one on a single element. I really like the $syntax as it allows for standard key/value binding syntax. To understand my perspective I'm coming from a string templating perspective. I looked at JSX the same way since the syntax supports it. It isn't any more or less magic than going `ref={markdown(props.note.markdown)}` just way cleaner. Same thing I liked about the $ control flow. It clearly had a marked purpose so you could immediately call out those elements as different and important, and again cut down extra syntax. I was fine moving off of that since it limited the extensibility of the library. But this is the exact opposite. I guess the fact I now have a concrete justification for not having them. I was sort of out on the subject, but I just don't appreciate TypeScript dictating what I do.

TypeScript seems to get in the way of everything. I am really trying to support it since people seem to like it. But for me, it is a constant dream-crusher. TypeScript feels like a bully out to steal my lunch money every week. Maybe this is why people avoid JSX with these sort of libraries. It's not JSX's fault though. I've seen talks where people say that it isn't doable with JSX to pull off what I'm doing here, etc why Svelte doesn't use it. But JSX has been great. But advances in JavaScript tooling wants to ruin my day. JSX is just syntax and has no contract on what it outputs but TypeScript has to make assumptions. For many things I can probably look at sidestepping tooling and providing own format like Svelte etc.. but TypeScript is this ubiquitous thing that really won't play nice.

As I said if you use forwardRef you already have the callback format today. And if I get rid of directives it seems like a reasonable thing. It just means though that if you want to have multiple of these you need like a combiner function. Hmm.. maybe there are other options to solve my issue. Accepting arrays of functions as well? I suppose there could be a combiner function, but that could sit in userland. Maybe see if this is a real problem before I worry about it. Maybe connected/disconnected element callbacks are just the thing.

I have to admit I've been using these patterns for years and never had a need for a lot of things people are looking at. But I'm thinking it might just be that I'm used to having a knowledge of the underlying DOM and scheduling mechanisms. I'm used to developers bucketting Reactive libraries in one place and VDOM in another. It is like Solid is taking people to this different zone where the expectations are that it conquers the best of both worlds. That's exciting. But it's incredibly challenging because this is really new ground.

I'm going to continue this conversation on the thread in Spectrum as well.

**Comment by ryansolid** [comment]
I am removing custom directives in the next version.. too much confusion. forwardRef is going to be the single way forward. Perhaps the naming isn't obvious but it also isnt contradictory ie.. you are forwarding a ref instead of assigning it. I think I will official support using forwardRef for directives. You will still need to schedule for after DOM connectivity via Promise/Timeout/afterEffects etc. I'm going to explore making better scheduling in the individual libraries but I think this plugin will only be responsible for passing references.

I'm going to consider this part of the issue done. If there is nothing else I'm going to close it.

**Comment by bluenote10** [comment]
Yes, the semantics of `forwardRef` are clear and explicit, makes sense to me. Thanks for the clarification!
