### ISSUE TITLE
Context based string binding vs JSX

### ISSUE THREAD

**Issue by mrjjwright** [ryansolid/babel-plugin-jsx-dom-expressions#4]
@ryansolid for the record, what exactly do you mean when you mention "context based HTML string binding" in your issues and contrast it with a jsx based approach.  What is a simple example of a fine grained lib using context based string binding?

**Comment by ryansolid** [comment]
KnockoutJS is the best example. But Ember, Angular, and Vue are variations on this.

Basically when you aren't using pre-compilation to JS code your options are HyperScript (React and like), Tagged Template Literals(lighterhtml) and string/HTML templates. String templates get sort of compiled at runtime. Generally instead of using a pure JS DSL like former methods they have a attribute or mustache based DSL to handle control flow. But that means everything is in these strings so there are no closures over state. All variables need to be placed in objects and as these context/scopes nest you tend to clone the parent context and add new keys to the object like the current iterated item in the list and index.

While Knockout is the best fine grained example (they even name contexts like $parent), DomC might be the easiest to look at for non-fined grain. If you look at how he clones the scope and sets variables on each iteration you get the idea.

**Comment by mrjjwright** [comment]
Makes perfect sense now, thanks!  And that makes a big difference for what I am doing actually as it leads me to believe that generating JS code is important for this reason, to use real scope and closures instead of artificially created ones.
