### ISSUE TITLE
[classList] Add support to set multiple CSS class names at once

### ISSUE THREAD

**Issue by r0skar** [ryansolid/babel-plugin-jsx-dom-expressions#6]
I came across this issue today and although there are plenty of workarounds, I still wanted to report it. I am using `scss` together with `css-modules` when creating Solid components. Thanks to `webpack`, this is simple to setup and works great.

Using `scss` allows for writing nested CSS:

```scss
.root {
  display: flex;
  flex-direction: column;

  &.first {
    border-top: $section-border;
  }
}
```

Thanks to `css-modules`, I can import these styles in my Solid component:

```js
import styles from 'styles.scss'

// `Section_rootpw9a0m7djuws0cx8 Section_rootpw9a0m7djuws0cx9`
console.log(styles.root)
```

Unfortunately, the generated CSS can not be used with `classList`, because it expects exactly one definition:

https://github.com/ryansolid/babel-plugin-jsx-dom-expressions/blob/212d0e35c959a1369033a4b4f7c59aba12efcca1/src/index.js#L67

Which leads to this error:

`Failed to execute 'toggle' on 'DOMTokenList': The token provided ('Section_rootpw9a0m7djuws0cx8 Section_rootpw9a0m7djuws0cx9') contains HTML space characters, which are not valid in tokens.`

P.S. As a workaround, I currently use [classcat](https://github.com/jorgebucaran/classcat) instead of `classList`.

**Comment by ryansolid** [comment]
Ok good catch. So what you are saying is we should be fine if it can support:

```js
{
  "class1 class2": true
}
```

So basically if I split the key by spaces we should be good?

**Comment by r0skar** [comment]
Yeah that would solve the issue.

**Comment by ryansolid** [comment]
I have fixed this by adding a classList helper to the runtime. That means along with getting 0.7.1 of this library you need to make sure your dom-expressions package is up to date (0.7.9).

**Comment by r0skar** [comment]
So, I have updated the two packages:

```json
"dom-expressions": "^0.7.9",
"babel-plugin-jsx-dom-expressions": "^0.7.1",
```

But now `classList` wont work at all:

`Uncaught TypeError: solid_js_dom__WEBPACK_IMPORTED_MODULE_8__.r.classList is not a function`

My code:

```jsx
<section classList={ ({ [styles.root]: true, [styles.first]: true, [styles.active]: true }) }>
  section
</section>
```

P.S. I have tried to reproduce the problem in a Codepen with `solid-standalone`, but `classList` has no affect at all. It is interpreted as a standard HTML attribute.

**Comment by ryansolid** [comment]
I haven't updated solid-standalone yet so I wouldn't have expected any behavior change since all the dependencies are bundled with it. Although I think I might know the issue looking closer. It looks like JSX classList and style currently only support dynamic expressions (ie... ones that are wrapped in parenthesis). They are older features and I will change them to handle both situations. But I don't believe this is your issue.

That error suggests that it isn't getting the right version of dom-expressions. I added r.classList in 0.7.9, and it's complaining it is not there(or rather not a function). The tests pass for this library, dom-expressions, lit-dom-expressions, and hyper-dom-expressions which all test this. So I'm wondering if it's possible two different versions of dom-expressions are being installed due to some remnants in the package-lock? Solid has a dependency on dom-expressions, but the other plugin-able render libraries only have peer dependencies.

**Comment by r0skar** [comment]
Thanks for the quick response. I had to re-install `solid-js` after upgrading `dom-expressions`, because node was still using `0.7.1` from when I originally installed `solid-js`. Everything works now and the original issue is solved as well!

> It looks like JSX classList and style currently only support dynamic expressions (ie... ones that are wrapped in parenthesis). They are older features and I will change them to handle both situations. But I don't believe this is your issue.

Yeah I noticed that too and was wondering why they are necessary, but didnt really dig into it.

**Comment by ryansolid** [comment]
Yeah it's because when I wrote this plugin the parens weren't required and I auto-wrapped everything. This had significant performance implications and was largely unnecessary.

Before I had started writing this library, I was testing Surplus with Solid.  Surplus tries to detect function calls () to decide to wrap, but that clearly broke Proxies which require none of that to access Signals. Adam Haile had suggested I just add the extra parens there to trick the Surplus compiler to wrap my state vars. It worked other than I was an avid CoffeeScript developer at the time and it kept getting compiled out. I proceeded with this library to try a whole string of different options until I realized that Proxies shouldn't be the special case but the decision to explicitly make something dynamic is. So in the vein of Angular or Polymer indicating 1 way versus 2 way binding I figured a simple syntax would work. Unfortunately JSX is sort of strict. So ironically I fell back on the original suggestion Adam gave me. I don't know if settled on the best syntax but it's very clean.

When I changed the syntax, I just changed it to only fire the wrap function with parens, so the special cases essentially got skipped when not wrapped. I never tested the non-dynamic cases for those bindings specifically and never noticed it.
