### ISSUE TITLE
Remove undefined props from HTMLElement

### ISSUE THREAD

**Issue by r0skar** [ryansolid/babel-plugin-jsx-dom-expressions#9]
When toggling HTML attributes, it would be nice if it were possible to have an  attribute removed from the element if its value is `undefined`. Right now, `undefined` is passed as a string, which in some cases breaks the expected functionality.

For example: I have a Video component with an optional prop `thumbnail`:

```
// App.js
<Video />

// Video.js
<video poster={ props.thumbnail }>
  ...
</video>
```

The above examples produces this DOM output:

```
<video poster="undefined">
  ...
</video>
```

This causes two problems: no thumbnail is shown and a `404` error is triggered. If the `poster` attribute were to be removed, these problems go away and additionally it will fallback to display the first frame of the video as a thumbnail.

**Comment by ryansolid** [comment]
Interesting. We're setting the property here rather an an attribute. If we were setting an attribute I'd get why this is happening, but since we are setting a property I don't control the attribute getting set. The video element is doing that all on it's own.

In fact document.getElementById("myVideo").poster = undefined does the same thing. They setup this property to always expect a string. That leaves a couple options: 

1. define special behavior for this JSX attribute specifically and tell the compiler to set it as an attribute instead of a property which should get coerced more intelligently to a string. This isn't unprecedented. href for example is always using the attribute since the property requires absolute paths and the attribute does relative pathing like hashes. But I'd prefer to avoid exception cases where possible.

2. Change the above code to:
```jsx
// App.js
<Video />

// Video.js
<video poster={ props.thumbnail || '' }>
  ...
</video>
```

I think perhaps the bigger awkwardness is the lack of defaultProps. Solid can't take advantage of destructuring default arguments since that access needs to be wrapped in a computation to be tracked. I'm not completely opposed to considering something like React's defaultProps but it would add overhead on every component function. It is also sort of awkward syntax.

```js
const Button = props => { ... }
Button.defaultProps = { text: 'OK' }
```
I could change the initialization to do this basically on every component function:
```js
Button(Object.assign({}, Button.defaultProps || {}, { text: 'Cancel', onClick: someHandler }))
```
Although this doesn't help with explicit undefineds as they'd overwrite the default. Perhaps this is what is missing here?

**Comment by r0skar** [comment]
Sorry for not checking it prior to opening the issue. I was convinced the behavior is related to the babel plugin and not the video element. Regarding the two options you mentioned, I agree that setting  exception cases is not desirable. It will most probably just cause more issues down the road. For my current use case, setting the default value to an empty string is exactly what I should have done in the beginning and what I will do now.

I am not so sure about `defaultProps`. I did occasionally use the feature with Vue, but it has a much nicer syntax. Looking at your example, the syntax is really awkward and although I`d choose to destruct default arguments if it was possible, I also like the explicitness of writing it like so:

```
const MyComponent = (props) => {
  const myProp = props.myProp || 'default value'
}
```

**Comment by ryansolid** [comment]
Yeah it's too bad that doesn't work in all cases given proxy or getter accessors you need to do not access the value until you are in the attribute expression or a computation. Same problem as rest destructuring in the function params. The only real opportunity to impose a default value ahead of time is when constructing the props object.

If it is deemed important enough React's version while I've always thought awkward is atleast common, and used by most React clones. I think the move to Hooks, and function components will see that version drop in popularity since destructuring is so easy. I will try to think of alternatives that fit with this approach. Could do it with a function I guess like:

```js
const MyComponent = (props) => {
  useDefaults(props, { myProp: 'default value' })
}
```
The positive is it's opt in. I actually think I like this. It's the same as _.defaults in that it doesn't clone the object (important not to remove getters).

**Comment by r0skar** [comment]
This looks great! Its opt-in and IMO it fits in with the general "style" of solid. If you were to implement default props, I´d vote for `useDefaults`.

**Comment by ryansolid** [comment]
I've set components now in this plugin to always pass an empty object even if there are no props. This enables the defaults. I've added a setDefaults (decided set was more appropriate name) that behaves like the useDefaults method described here to Solid in it's next version (0.7.0).
